# Generated by Django 5.2.6 on 2025-10-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title', 'product_qty'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('title', 'open_time'), 'verbose_name': 'Секція', 'verbose_name_plural': 'Секції'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
