# Generated by Django 5.2.6 on 2025-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='title',
            field=models.CharField(default='uwu', max_length=64),
        ),
    ]
